bundler_args: --without development
script: "bundle exec rake db:drop db:create db:migrate spec"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.9.2
  - ree
gemfile:
  - Gemfile
notifications:
  recipients:
    - charles.feduke@gmail.com